### PR TITLE
UWHRD-1181 - Bynder UIE using Bynder Compact View v2

### PR DESCRIPTION
**Pull request by rochaeb**

### CODE REVIEW

**Review by camiloriosf — APPROVED** [review]
LGTM

**Comment by spindle79** [comment]
@rochaeb Can you rebase and resubmit the PR?   Please ping @camiloriosf and I when ready.

**Comment by rochaeb** [comment]
> @rochaeb Can you rebase and resubmit the PR? Please ping @camiloriosf and I when ready.

Done

**Review by spindle79 — APPROVED** [review]
LGTM

**Pull request merged**
